global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 5s


# A scrape configuration containing endpoints to scrape:

scrape_configs:
# cAdvsior and PushGateway are started in son-emu
  - job_name: 'cAdvisor'

    scrape_interval: 1s

    static_configs:
      - targets: ['172.17.0.1:8081']

# Pushgateway started in SP
  - job_name: 'PushGateway'

    scrape_interval: 1s

    static_configs:
      - targets: ['172.17.0.1:9091']



