version: '2'


services:

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
     - "9091:9091"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    # get the prometheus config file
    volumes:
     - /tmp/son-monitor:/etc/prometheus
    ports:
     - "9090:9090"
    command: [-config.file=/etc/prometheus/prometheus_sdk.yml]
    links:
     - pushgateway
     - cadvisor

  cadvisor:
   image: google/cadvisor
   container_name: cadvisor
   volumes:
    - "/:/rootfs:ro"
    - "/var/run:/var/run:rw"
    - "/sys:/sys:ro"
    - "/var/lib/docker/:/var/lib/docker:ro"
   ports:
    - "8090:8080"



