- hosts: localhost

  tasks:
    - name: updates apt
      apt: update_cache=yes

    - name: install python 3.4
      apt: pkg={{item}} state=installed
      with_items:
        - python3.4
        - libyaml-dev

    - name: install pip 3.x
      apt: pkg=python3-pip state=installed

    - name: install son-monitor dependecies
      apt: pkg={{item}} state=installed
      with_items:
        - libffi-dev
        - libssl-dev
        - tcpdump

    - name: download docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.6.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: install docker-compose
      shell: "{{ item }}"
      with_items:
        - chmod +x /usr/local/bin/docker-compose
