- hosts: localhost

  tasks:
    - name: updates apt
      apt: update_cache=yes

    - name: install son-cli dependencies
      apt: pkg={{item}} state=installed
      with_items:
        - software-properties-common
        - apt-transport-https
        - ca-certificates wget
        - python3.4
        - python3.pip
        - python3-pycparser
        - build-essential
        - python3-dev
        - python3-pip
        - libyaml-dev

    - name: ensure docker repo key
      shell: curl -fsSL https://get.docker.com/gpg | apt-key add -

    - name: install docker
      shell: curl -fsSL https://get.docker.com/ | sh

    - name: install son-monitor dependecies
      apt: pkg={{item}} state=installed
      with_items:
        - libffi-dev
        - libssl-dev
        - tcpdump

    - name: download docker-compose
      shell: curl -L "https://github.com/docker/compose/releases/download/1.10.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

    - name: install docker-compose
      shell: "{{ item }}"
      with_items:
        - chmod +x /usr/local/bin/docker-compose
